[package]
name = "messaging"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
serde.workspace = true
kafka.workspace = true
apache-avro.workspace = true
log.workspace = true
shared.workspace = true

domain = { path = "../domain" }
application = { path = "../application" }